# Generated by Django 4.2.15 on 2024-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Document')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Document')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
