# Generated by Django 4.2.15 on 2024-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Document'),
        ),
    ]
