# Generated by Django 4.2.15 on 2024-10-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0002_userdocuments_email_alter_userdocuments_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocuments',
            name='email',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Email'),
        ),
    ]
