# Generated by Django 4.2.15 on 2024-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0008_alter_certifieddocumentupload_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifieddocumentupload',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
