# Generated by Django 5.1.3 on 2024-11-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0011_alter_certifieddocumentupload_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
