# Generated by Django 5.1.4 on 2025-01-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0012_userdocuments_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_face', models.ImageField(blank=True, null=True, upload_to='image_id/', verbose_name='Document')),
                ('recognised_face', models.ImageField(blank=True, null=True, upload_to='recognised_face/', verbose_name='Document')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='Stamp/', verbose_name='Document')),
                ('uploaded_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('pdf_path', models.FileField(upload_to='verified_documents/')),
            ],
        ),
    ]
