# Generated by Django 5.1.4 on 2025-01-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certierApp', '0013_userfaceverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfaceverification',
            old_name='id_face',
            new_name='id_back_face',
        ),
        migrations.AddField(
            model_name='userfaceverification',
            name='id_front_face',
            field=models.ImageField(blank=True, null=True, upload_to='image_id/', verbose_name='Document'),
        ),
    ]
